#!/usr/bin/env python

import os
import pystache  # https://github.com/defunkt/pystache
import yaml  # https://pypi.python.org/pypi/PyYAML/

class Aurorean:
    def __init__(self, configfile):
        self.config = self._loadConfig(configfile)

    def _loadConfig(self, filename):
        # default configuration
        config = {'outputdir': 'site',
                  'pagetitle': 'Aurorean',
                  'latt':'35.9605556',
                  'long':'-83.9208333',
                  'name':'Downtown Knoxville', # should be segmented off
                 }

        # load configfile
        if os.path.exists(filename):
            with open(filename, 'r') as handle:
                yaml_config = yaml.load(handle)
                if yaml_config is not None:
                    config.update(yaml_config)
        else:
            print "Did not find config file '%s' using defaults" % filename

        return config


if __name__ == "__main__":
    builder = Aurorean("aurorean.yaml")

    with open('index.html.in', 'r') as handle:
        template = handle.read()


    renderer = pystache.Renderer(#missing_tags='strict',
                                 search_dirs=['partials'])
    finaltext=renderer.render(template, builder.config)

    if not os.path.exists(builder.config['outputdir']):
        os.mkdir(builder.config['outputdir'])

    with open(os.path.join(builder.config['outputdir'],'index.html'), 'w') \
            as handle:
        handle.write(finaltext)

    print "Done"
