#!/usr/bin/env python

import os
import pystache  # https://github.com/defunkt/pystache
import yaml  # https://pypi.python.org/pypi/PyYAML/

class Aurorean:
    def __init__(self, configfile):
        self.config = self._loadConfig(configfile)

    def _loadConfig(self, filename):
        # default configuration
        config = {'outputdir': 'site',
                  'pagetitle': 'Aurorean',
                  'forecastio':{'name':'Downtown Knoxville',
                                'latt':'35.9605556',
                                'long':'-83.9208333'},
                 }

        # load configfile
        if os.path.exists(filename):
            with open(filename, 'r') as handle:
                yaml_config = yaml.load(handle)
                if yaml_config is not None:
                    config.update(yaml_config)
        else:
            print "Did not find config file '%s' using defaults" % filename

        return config

    def render(self):
        with open('index.html.in', 'r') as handle:
            template = handle.read()

        renderer = pystache.Renderer(missing_tags='strict',
                                     search_dirs=['partials'])
        finaltext=renderer.render(template, self.config)

        outputdir = self.config['outputdir']
        if not os.path.exists(outputdir):
            os.mkdir(outputdir)

        with open(os.path.join(outputdir,'index.html'), 'w') \
             as handle:
            handle.write(finaltext)



if __name__ == "__main__":
    builder = Aurorean("aurorean.yaml")
    builder.render()
